export const GET_CHARACTERS = "GET_CHARACTERS";
export const GET_RANDOM_CHARACTERS = "START_GAME";
export const GET_SELECTED_MEMOCARD = "GET_SELECTED_MEMOCARD";
export const GET_ANIMATION = "GET_ANIMATION";
export const GET_SHIFTS = "GET_SHIFTS";
export const GET_SUCCESS= "GET_SUCCESS";